# Generated by Django 6.0 on 2025-12-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_tag_alter_article_options_articlescope_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='scope',
        ),
    ]
